name: Continuous Integration

on:
  push:
    branches:
      - "pipeline-update"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Create screenshots folder
        run: mkdir -p ./screenshots

      - name: Running E2E tests
        run: npm run wdio
        continue-on-error: true

      # - name: Upload Allure raw results
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: allure-results
      #     path: allure-results

      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report

      # Upload the generated HTML report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report
      

       - name: Upload Allure Report to Public Repo
        if: always()
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          TARGET_REPO: "usama-arbisoft1/agoda-reports.git"
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

          # Clone the target repository
          git clone https://$PAT_TOKEN@github.com:$TARGET_REPO
          
          # Copy Allure report to the target repo
          cp -r allure-report/* $TARGET_REPO/allure-report/
          
          cd $TARGET_REPO

          # Stage and commit the changes
          git add .
          git commit -m "Upload Allure report from pipeline"

          # Push the changes to the main branch
          git push origin main

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: ./screenshots
