name: Continuous Integration

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Install Chromium
      #   run: sudo apt-get install chromium-browser
      # - name: Install dependencies for headless Chrome
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y \
      #     libappindicator3-1 fonts-liberation \
      #     libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 \
      #     libgbm1 libnspr4 libnss3 libx11-xcb1 libxcomposite1 libxcursor1 \
      #     libxdamage1 libxrandr2 libxss1 xdg-utils
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22.x

      - run: npm install
        name: Install dependencies

      - name: Create screenshots folder
        run: mkdir -p ./screenshots

      # This is where you could build your app
      # You could also start your server process (take a look at https://github.com/Slashgear/slashgear.github.io/blob/source/.github/workflows/continuous-integration.yml)

      # Run your test with the same command you uses locally
      - run: npx wdio run ./wdio.conf.ts --spec ./test/specs/test.spec.ts
        name: Running E2E tests
        continue-on-error: true

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: ./screenshots
